<%@ Page Title="" Language="C#" MasterPageFile="~/people.Master" AutoEventWireup="true" CodeBehind="viewtradersyn.aspx.cs" Inherits="OPLS.Peoples.viewtradersyn" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div class="headings" 
         style="background-color: #800000; border: 1px inset #000000; width: 99.8%; height: 25px"> 
         
        <h1 style="font-family: Arial, Helvetica, sans-serif; font-size: medium; font-weight: bolder; font-style: normal; font-variant: normal; text-transform: none; color: #FFFFCC; margin-top: 0px;" align="center"> 
            &nbsp;Item You Supplied  </h1>

         
         </div>
         <br /> 
     
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
    BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" 
    CellPadding="3" DataSourceID="SqlDataSource1" ForeColor="Black" 
    GridLines="Vertical" AutoGenerateDeleteButton="True" 
    AutoGenerateEditButton="True" Width="100%">
        <AlternatingRowStyle BackColor="#CCCCCC" />
        <Columns>
            <asp:BoundField DataField="Trader" HeaderText="Trader" 
                SortExpression="Trader" />
            <asp:BoundField DataField="Clothes" HeaderText="Clothes" 
                SortExpression="Clothes" />
            <asp:BoundField DataField="Brand" HeaderText="Brand" SortExpression="Brand" />
            <asp:BoundField DataField="Date" HeaderText="Date" SortExpression="Date" />
            <asp:BoundField DataField="msg" HeaderText="msg" SortExpression="msg" />
            <asp:BoundField DataField="RID" HeaderText="RID" SortExpression="RID" />
        </Columns>
        <FooterStyle BackColor="#CCCCCC" />
        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F1F1F1" />
        <SortedAscendingHeaderStyle BackColor="#808080" />
        <SortedDescendingCellStyle BackColor="#CAC9C9" />
        <SortedDescendingHeaderStyle BackColor="#383838" />
    </asp:GridView>


<asp:SqlDataSource ID="SqlDataSource1" runat="server" 
    ConnectionString="<%$ ConnectionStrings:ConnectionString2 %>" 
    
    SelectCommand="SELECT [Trader], [Clothes], [Brand], [Date], [msg], [RID] FROM [TraderSYN] WHERE ([RID] = @RID)">
    <SelectParameters>
        <asp:SessionParameter Name="RID" SessionField="RID" Type="String" />
    </SelectParameters>
</asp:SqlDataSource>


</asp:Content>
